"""Supabase 连接 - 单例模式"""

import os
from typing import Any, Optional, Dict
from threading import Lock
from supabase import create_client, Client
from ymda.settings import Settings
from ymda.utils.logger import get_logger

logger = get_logger(__name__)


class Database:
    """数据库连接管理器 - Supabase（单例模式）"""
    
    _instance: Optional['Database'] = None
    _lock = Lock()
    
    def __new__(cls, settings: Optional[Settings] = None):
        """单例模式实现"""
        if cls._instance is None:
            with cls._lock:
                if cls._instance is None:
                    if settings is None:
                        # 尝试从环境变量创建 Settings
                        settings = Settings()
                    cls._instance = super().__new__(cls)
                    cls._instance._initialized = False
        return cls._instance
    
    def __init__(self, settings: Optional[Settings] = None):
        """初始化数据库连接（仅在首次调用时执行）"""
        if hasattr(self, '_initialized') and self._initialized:
            return
        
        if settings is None:
            # 尝试从环境变量创建 Settings
            settings = Settings()
        
        self.settings = settings
        self.client: Optional[Client] = None
        self._connect()
        self._initialized = True
    
    def _connect(self):
        """
        连接到 Supabase
        
        supabase-py 库会自动设置以下 headers:
        - apikey: {supabase_key}
        - Authorization: Bearer {supabase_key}
        """
        try:
            # 详细检查配置项
            missing_configs = []
            if not self.settings.supabase_url:
                missing_configs.append("SUPABASE_URL")
            if not self.settings.supabase_key:
                missing_configs.append("SUPABASE_SERVICE_ROLE_KEY 或 SUPABASE_KEY")
            
            if missing_configs:
                logger.warning(
                    f"Supabase配置不完整，无法连接数据库。缺失的配置项: {', '.join(missing_configs)}。"
                    f"请检查 .env 文件或环境变量是否已正确设置。"
                )
                return
            
            # 检查是否使用了 service_role key（推荐用于服务端操作）
            is_service_role = os.getenv("SUPABASE_SERVICE_ROLE_KEY") is not None
            if not is_service_role:
                logger.warning(
                    "⚠️  警告: 未检测到 SUPABASE_SERVICE_ROLE_KEY，使用的是 SUPABASE_KEY。"
                    "对于数据库写入操作，强烈建议使用 service_role key（绕过 RLS 限制）。"
                    "anon key 可能因权限不足导致 401 错误。"
                )
            
            # 创建 Supabase 客户端
            # supabase-py 库会自动设置以下 headers（与 requests 示例一致）:
            # - apikey: {supabase_key}
            # - Authorization: Bearer {supabase_key}
            # - Content-Type: application/json
            self.client = create_client(
                self.settings.supabase_url,
                self.settings.supabase_key
            )
            
            key_type = "service_role" if is_service_role else "anon/key"
            logger.info(
                f"Supabase数据库连接成功（单例）- URL: {self.settings.supabase_url[:30]}... "
                f"Key类型: {key_type}，已自动设置 apikey 和 Authorization Bearer headers"
            )
        except Exception as e:
            error_msg = str(e)
            # 检查是否是认证错误
            if '401' in error_msg or 'Invalid API key' in error_msg or 'Unauthorized' in error_msg:
                logger.error(
                    f"连接Supabase失败（认证错误）: {error_msg}\n"
                    f"💡 提示: 请确保使用的是有效的 service_role key 或 anon key。"
                    f"supabase-py 库会自动设置 apikey 和 Authorization Bearer headers。"
                )
            else:
                logger.error(f"连接Supabase失败: {error_msg}")
            raise
    
    def get_client(self) -> Client:
        """获取数据库客户端"""
        if not self.client:
            raise RuntimeError("Database client not initialized. 请检查Supabase配置。")
        return self.client
    
    def is_connected(self) -> bool:
        """检查数据库是否已连接"""
        return self.client is not None
    
    def create_ym_table_if_not_exists(self) -> bool:
        """
        创建 ym 表（如果不存在）
        
        Returns:
            成功返回 True，失败返回 False
        """
        create_table_sql = """
        CREATE TABLE IF NOT EXISTS public.ym (
          id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          slug         TEXT NOT NULL UNIQUE,
          name         TEXT NOT NULL,
          category     TEXT NOT NULL,
          description  TEXT,
          created_at   TIMESTAMPTZ DEFAULT now(),
          updated_at   TIMESTAMPTZ DEFAULT now()
        );
        
        CREATE INDEX IF NOT EXISTS idx_ym_slug ON public.ym(slug);
        CREATE INDEX IF NOT EXISTS idx_ym_category ON public.ym(category);
        """
        
        result = self.execute_sql_via_management_api(create_table_sql)
        if result:
            logger.info("✓ ym 表创建成功或已存在")
            return True
        else:
            logger.warning("⚠ 无法通过 Management API 创建表，请手动在 Supabase Dashboard 中创建")
            return False
    
    def execute_sql_via_management_api(self, sql: str) -> Optional[Dict[str, Any]]:
        """
        通过 Management API 执行 SQL 查询
        
        Args:
            sql: 要执行的 SQL 语句
            
        Returns:
            查询结果字典，如果失败则返回 None
        """
        if not self.settings.supabase_access_token or not self.settings.supabase_project_id:
            logger.warning(
                "Management API 配置不完整，无法执行 SQL。"
                "需要设置 SUPABASE_ACCESS_TOKEN 和 SUPABASE_PROJECT_ID。"
            )
            return None
        
        try:
            import requests
            
            # Management API endpoint for executing SQL
            mgmt_base = "https://api.supabase.com"
            mgmt_url = f"{mgmt_base}/v1/projects/{self.settings.supabase_project_id}/database/query"
            
            headers = {
                'Authorization': f'Bearer {self.settings.supabase_access_token}',
                'Content-Type': 'application/json',
            }
            
            payload = {
                'query': sql
            }

            print(payload)
            
            response = requests.post(mgmt_url, headers=headers, json=payload, timeout=30)
            
            if response.status_code in (200, 201):
                logger.info("✓ SQL 执行成功 (via Management API)")
                return response.json()
            elif response.status_code == 400:
                error_msg = response.text[:200]
                logger.error(f"✗ SQL 执行失败 (语法错误): {error_msg}")
                return None
            elif response.status_code == 401:
                logger.error(
                    "⚠ Management API 认证失败。"
                    "access_token 可能没有所需权限或已过期。"
                )
                return None
            elif response.status_code == 404:
                logger.error(
                    "⚠ Management API 端点未找到。"
                    "请检查 SUPABASE_PROJECT_ID 是否正确。"
                )
                return None
            else:
                logger.error(
                    f"⚠ Management API 返回 {response.status_code}: {response.text[:200]}"
                )
                return None
        except ImportError:
            logger.error("⚠ requests 库未安装，无法使用 Management API")
            return None
        except Exception as e:
            logger.error(f"Management API 执行失败: {e}")
            return None
    
    def close(self):
        """关闭数据库连接"""
        logger.info("Closing database connection")
        self.client = None
        Database._instance = None
        self._initialized = False


def get_database(settings: Optional[Settings] = None) -> Optional[Database]:
    """
    获取数据库单例实例（推荐使用此方法获取数据库实例）
    
    Args:
        settings: Settings 实例（可选，首次调用时如果不提供则从环境变量创建）
        
    Returns:
        Database 实例，如果配置不完整或连接失败则返回 None
    """
    try:
        if settings is None:
            settings = Settings()
        
        # 在创建 Database 之前先检查配置
        if not settings.supabase_url or not settings.supabase_key:
            missing = []
            if not settings.supabase_url:
                missing.append("SUPABASE_URL")
            if not settings.supabase_key:
                missing.append("SUPABASE_KEY 或 SUPABASE_SERVICE_ROLE_KEY")
            logger.warning(
                f"数据库配置不完整，无法初始化连接。缺失配置: {', '.join(missing)}。"
                f"请确保 .env 文件存在且包含必要的配置项。"
            )
            return None
        
        db = Database(settings)
        if not db.is_connected():
            logger.warning("数据库连接未建立，请检查配置和网络连接")
            return None
        return db
    except Exception as e:
        logger.error(f"初始化数据库连接失败: {e}")
        return None

